import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import './functional.css';

const stages=['DOCUMENTS INGESTED','OCR COMPLETE','KNOWLEDGE RETRIEVED','P&ID ANALYZED','CALCULATIONS VERIFIED','EVIDENCE CROSS-CHECKED','REPORT GENERATED'];
const pipeline=[['01','OCR','Extract'],['02','RAG','Retrieve'],['03','VISION','Understand'],['04','CALCULATE','Verify numbers'],['05','REASON','Cross-reference'],['06','VERIFY','Validate evidence'],['07','REPORT','Generate output']];
const API_BASE_URL=import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8787';

function Ripple(){
 const ref=useRef(null); const pointer=useRef({x:50,y:25,tx:50,ty:25});
 useEffect(()=>{const el=ref.current; let frame; const move=e=>{const p=e.touches?.[0]||e;const r=el.getBoundingClientRect();pointer.current.tx=(p.clientX-r.left)/r.width*100;pointer.current.ty=(p.clientY-r.top)/r.height*100};
  const loop=()=>{const p=pointer.current;p.x+=(p.tx-p.x)*.08;p.y+=(p.ty-p.y)*.08;el.style.setProperty('--x',p.x+'%');el.style.setProperty('--y',p.y+'%');frame=requestAnimationFrame(loop)}; loop(); window.addEventListener('pointermove',move,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('pointermove',move)}} ,[]);
 return <div className="atmosphere" ref={ref}><i/><i/><i/></div>
}
function Arrow(){return <span className="arrow">↓</span>}
function App(){
 const [running,setRunning]=useState(false),[complete,setComplete]=useState(false),[active,setActive]=useState(-1),[job,setJob]=useState(null),[apiError,setApiError]=useState(''),[health,setHealth]=useState(null),[uploaded,setUploaded]=useState([]); const poll=useRef();
 useEffect(()=>{fetch(`${API_BASE_URL}/health`).then(r=>r.json()).then(setHealth).catch(()=>setHealth({llm:{status:'API OFFLINE'},ocr:{status:'API OFFLINE'}}));return()=>clearInterval(poll.current)},[]);
 const start=async()=>{if(running)return;setApiError('');try{const url=uploaded.length?`${API_BASE_URL}/api/analysis`:`${API_BASE_URL}/api/demo/run`,options=uploaded.length?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documents:uploaded})}:{method:'POST'};const r=await fetch(url,options);if(!r.ok)throw Error('Local API rejected the analysis run.');const {jobId}=await r.json();setJob(jobId);setRunning(true);setComplete(false);setActive(-1);poll.current=setInterval(async()=>{try{const data=await fetch(`${API_BASE_URL}/api/jobs/${jobId}`).then(x=>x.json());setActive(data.stages.filter(s=>s.status==='COMPLETED').length-1);if(data.status==='COMPLETED'){clearInterval(poll.current);setRunning(false);setComplete(true)}if(data.status==='FAILED'){clearInterval(poll.current);setRunning(false);setApiError(data.error||'Analysis failed.')}}catch{clearInterval(poll.current);setRunning(false);setApiError('Lost connection to the local API.')}},200)}catch(e){setApiError(e.message)}};
 const upload=async(files)=>{const body=new FormData();[...files].forEach(f=>body.append('documents',f));try{const r=await fetch(`${API_BASE_URL}/api/documents`,{method:'POST',body}),data=await r.json();if(!r.ok)throw Error(data.error);setUploaded(data.documents);setApiError('')}catch(e){setApiError(e.message)}};
 return <main><Ripple/><nav><a className="brand" href="#top"><b>SO</b><span>SOVEREIGN</span></a><div className="navlinks"><a href="#system">SYSTEM</a><a href="#proof">EVIDENCE</a><a href="#workbench">WORKBENCH</a></div><button className="nav-status"><em/>LOCAL / AIR-GAPPED</button></nav>
 <section id="top" className="hero"><div className="hero-copy reveal"><p className="eyebrow">SOVEREIGN AGENTIC AI WORKBENCH</p><h1>PRIVATE<br/><i>INTELLIGENCE.</i><br/>BUILT TO EXECUTE.</h1><p className="lede">An air-gapped multimodal AI workbench that transforms sensitive documents into verified, decision-ready outputs — without sending your data to the cloud.</p><div className="actions"><a className="btn dark" href="#workbench">LAUNCH WORKBENCH <b>↗</b></a><a className="btn ghost" href="#system">EXPLORE THE SYSTEM <b>↓</b></a></div></div>
 <div className="core-scene" aria-label="Documents feeding a Sovereign AI core"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className="wire w1"/><div className="wire w2"/><div className="wire w3"/><div className="wire w4"/>
 {[['Inspection','REPORT','tl'],['Safety','MANUAL','tr'],['P&ID','DRAWING','bl'],['Equipment','DATA','br']].map(x=><div className={'doc '+x[2]} key={x[2]}><span>◫</span><small>{x[0]}</small><strong>{x[1]}</strong></div>)}
 <div className="ai-core"><div className="core-ring"/><div className="core-ring r2"/><span>SO</span><small>SOVEREIGN<br/>AI CORE</small></div><div className="output"><span>✓</span><small>VERIFIED</small><strong>REPORT</strong></div></div>
 <div className="scroll-cue"><span/>SCROLL TO EXPLORE</div></section>
 <section id="system" className="privacy section"><div className="section-num">01 / PRIVATE BY DESIGN</div><div className="privacy-grid"><h2>Your data never<br/><i>leaves the room.</i></h2><div className="local-flow"><div>DATA</div><Arrow/><div>LOCAL<br/>MACHINE</div><Arrow/><div>LOCAL<br/>MODELS</div><Arrow/><div>LOCAL<br/>OUTPUT</div></div></div><div className="chips"><span><em/>INTERNET DISCONNECTED</span><span><em/>LOCAL INFERENCE</span><span><em/>PRIVATE DATA</span><span><em/>AIR-GAPPED READY</span></div></section>
 <section className="contrast section"><div className="section-num">02 / NOT ANOTHER DOCUMENT CHATBOT</div><h2>Answers are cheap.<br/><i>Proof is everything.</i></h2><div className="compare"><div className="old"><p>TRADITIONAL AI</p><div>UPLOAD <Arrow/> ASK <Arrow/> ANSWER</div><small>A response without operational context.</small></div><div className="new"><p>SOVEREIGN WORKBENCH</p><div>{['UPLOAD','UNDERSTAND','RETRIEVE','ANALYZE','CALCULATE','VERIFY','GENERATE'].map((x,i)=><React.Fragment key={x}><b>{x}</b>{i<6&&<Arrow/>}</React.Fragment>)}</div><small>A decision, backed by every source of truth.</small></div></div></section>
 <section className="sources section"><div className="source-copy"><div className="section-num">03 / MULTIMODAL REASONING</div><h2>One question.<br/><i>Four sources of truth.</i></h2><p>Every conclusion is cross-referenced across the complete operating context — documents, drawings and live equipment data.</p></div><div className="source-map"><div className="source-list">{['Inspection Report','Safety Manual','P&ID Diagram','Equipment Excel'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<b>↗</b></div>)}</div><div className="reasoning">REASONING<br/>LAYER <span>✦</span></div></div></section>
 <section className="pipeline section"><div className="section-num">04 / THE INTELLIGENCE PIPELINE</div><div className="pipeline-top"><h2>Designed to<br/><i>show its work.</i></h2><p>Every stage is inspectable. Every result is traceable.</p></div><div className="pipeline-grid">{pipeline.map(([n,title,desc],i)=><div className="p-node" key={title}><small>{n}</small><b>{title}</b><span>{desc}</span><i>{i===6?'↗':'→'}</i></div>)}</div></section>
 <section id="proof" className="proof section"><div className="proof-title"><div className="section-num">05 / EVIDENCE-BASED REASONING</div><h2>Not a black box.<br/><i>A clear line of sight.</i></h2></div><div className="analysis-card"><header><span className="pulse"/> LIVE ANALYSIS <small>PV-204 / PRESSURE VESSEL</small></header><h3>Is equipment PV-204 operating within specification?</h3><div className="evidence"><div><b>INSPECTION REPORT</b><span>Pressure: <strong>8.4 bar</strong></span></div><div><b>SAFETY MANUAL</b><span>Maximum: <strong>10 bar</strong></span></div><div><b>P&ID DRAWING</b><span>Equipment identified: <strong>PV-204</strong></span></div><div><b>EQUIPMENT EXCEL</b><span>Last inspection: <strong>21 days ago</strong></span></div></div><div className="calculation"><span>8.4 <small>/ 10 BAR</small></span><b>= 84%</b><div><em>✓</em> WITHIN SPECIFICATION</div></div></div></section>
<section id="workbench" className="workbench section"><div className="section-num">06 / INTERACTIVE WORKBENCH</div><div className="bench"><aside><a className="brand"><b>SO</b></a>{['WORKBENCH','DOCUMENTS','KNOWLEDGE BASE','ANALYSIS RUNS','REPORTS','MODELS','SYSTEM STATUS'].map((x,i)=><span className={i===0?'selected':''} key={x}>{x}</span>)}<footer><em/> LOCAL MODE<br/><small>INTERNET: DISCONNECTED</small></footer></aside><div className="bench-main"><header><div><small>WORKBENCH / SESSION 012</small><h3>Sovereign Workbench</h3></div><div className="sys"><em/> SYSTEM READY</div></header><div className="upload-grid">{['Inspection Report','Safety Manual','P&ID Drawing','Equipment Excel'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><small>READY FOR ANALYSIS</small><i>✓</i></div>)}</div><div className="upload-action"><label>UPLOAD DOCUMENTS<input aria-label="Upload technical documents" type="file" accept=".pdf,.docx,.png,.jpg,.jpeg,.xlsx,.csv" multiple onChange={e=>upload(e.target.files)}/></label><small>{uploaded.length?`${uploaded.length} document(s) processed locally`:'PDF · DOCX · PNG · JPG · XLSX · CSV'}</small></div>{uploaded.length>0&&<div className="uploaded-list">{uploaded.map(d=><div key={d.id}><b>{d.status==='COMPLETED'?'✓':'!'}</b> {d.name}<small>{d.processing}{d.warnings?.[0]?` — ${d.warnings[0]}`:''}</small></div>)}</div>}<div className="runzone"><div><small>ANALYSIS SCOPE</small><b>Compliance & operational verification</b></div><button onClick={start} className="btn dark">{running?'ANALYZING…':'RUN LIVE ANALYSIS'} <b>↗</b></button></div><div className="live-log">{stages.map((x,i)=><div className={(i<=active&&running)||complete?'done':i===active?'current':''} key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}<b>{(i<active||complete)?'✓':i===active&&running?'•••':''}</b></div>)}{complete&&<div className="complete">ANALYSIS COMPLETE <a href={`${API_BASE_URL}/api/jobs/${job}/report.pdf`}>REPORT PDF ↗</a> <a href={`${API_BASE_URL}/api/jobs/${job}/report.docx`}>DOCX ↗</a></div>}{apiError&&<p className="api-error" role="alert">{apiError}</p>}<div className="live-status">GPU: {health?.gpu?.name||'CHECKING'} · LLM: {health?.llm?.status||'CHECKING'} · VISION: {health?.vision?.status||'CHECKING'} · OCR: {health?.ocr?.status||'CHECKING'} · <strong>DEMO OUTPUT IS SIMULATED</strong></div></div></div></div></section>
 <section className="report section"><div><div className="section-num">07 / DECISION-READY OUTPUT</div><h2>From raw data<br/>to a report that<br/><i>moves decisions.</i></h2><p>A clear professional output with full evidence, calculations and recommended actions.</p><div className="actions"><a className="btn dark" href={job?`${API_BASE_URL}/api/jobs/${job}/report.pdf`:undefined} onClick={e=>{if(!job){e.preventDefault();setApiError('Run the demo analysis before exporting a report.')}}}>EXPORT PDF ↗</a><a className="btn ghost" href={job?`${API_BASE_URL}/api/jobs/${job}/report.docx`:undefined} onClick={e=>{if(!job){e.preventDefault();setApiError('Run the demo analysis before exporting a report.')}}}>EXPORT DOCX ↗</a></div></div><article className="report-paper"><small>SOVEREIGN / VERIFIED REPORT</small><h3>Operational<br/>Compliance Review</h3><hr/><p>EXECUTIVE SUMMARY</p><b>PV-204 is operating within approved pressure limits.</b><ul><li>Equipment Analysis</li><li>Safety Verification</li><li>Evidence & Calculations</li><li>Risk Assessment</li><li>Recommendations</li></ul><footer>CONFIDENTIAL · LOCAL GENERATION</footer></article></section>
 <footer className="footer"><a className="brand"><b>SO</b><span>SOVEREIGN</span></a><p>PRIVATE INTELLIGENCE FOR CRITICAL OPERATIONS.</p><span>© 2026 SOVEREIGN SYSTEMS</span></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
